name: legal_dost
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.0
  image_picker: ^1.0.7  # Updated to latest
  cached_network_image: ^3.2.3
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  http: ^1.2.0
  url_launcher: ^6.3.0
  speech_to_text: ^7.0.0
  firebase_core: ^3.6.0  # Consider updating to ^3.7.0 or latest
  firebase_auth: ^5.2.0  # Consider updating to ^5.3.0 or latest
  cloud_firestore: ^5.3.0  # Consider updating to ^5.4.0 or latest
  uuid: ^4.4.0
  firebase_storage: ^12.4.4  # Ensure compatibility with other Firebase packages
  image: ^4.2.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  mockito: ^5.4.4
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/loader.gif
    - assets/app_icon/  # Keep for reference, but launcher uses image_path

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon/app_icon.png"  # Ensure this file exists
  #min_sdk_android: 21  # Optional, adjust if needed
  # Optional: Add adaptive icon settings if needed
  #adaptive_icon_background: "#19DBD6"
  # adaptive_icon_foreground: "#19DBD6"